lastupdate: "/Users/myuser/Library/Application Support/mastopost/lastupdate.gob"
url: https://example.com/feed/
clientid: mastodon_client_id
clientsec: mastodon_client_secret
token: mastodon_access_token
instance: https://example.com
lambdaFunctions:
  mastopost-rss-crossposter:
    - functionArn: arn:aws:lambda:us-east-1:xxxxxxxxxxxx:function:mastopost-rss-crossposter
